### ISSUE TITLE
How to test with custom dataset?

### ISSUE THREAD

**Issue by eris231** [dragonbook/V2V-PoseNet-pytorch#3]
Hi,

I've trained your pytorch version model using the MSRA dataset and it works well, and the next step I'd like to use the trained model to run on my own dataset, may I ask how to prepare the centered data like the paper described?

Thanks!

**Comment by dragonbook** [comment]
Hi eris231,

What's your dataset ? If you are doing experiment on hand depth images like MSRA dataset, you could firstly try the way the paper does. If you have any further questions on that, you may also ask the paper's author directly on his [repo](https://github.com/mks0601/V2V-PoseNet_RELEASE)(since I have not computed the center yet).

**Comment by eris231** [comment]
Hi dragonbook,

I am trying to use this model to get the 3D coordinate from the depth image I recorded myself, and since the paper has described another network for center calculation, I was wondering if you have any plan to implement that.

Thanks

**Comment by dragonbook** [comment]
Hi eris231,

I have no plan right now. This repository just only confirmed that the main model can work. You need to search some hand location implementations or implement one by yourself.

**Comment by eris231** [comment]
ok thanks for reply!

**Comment by ElegantLin** [comment]
@eris231 Do you find a method to find the center? Thanks!
