### ISSUE TITLE
can't work well in NYU

### ISSUE THREAD

**Issue by DongGuaDONG** [dragonbook/V2V-PoseNet-pytorch#4]
Your code works fine in the MSRA dataset. I changed the code to the NYU dataset. The precision is not up to the torch7 version. I used your parameter settings with an accuracy of 13mm, using the author's parameter settings. 10mm, what do you think is the reason?

**Comment by DongGuaDONG** [comment]
[nyu.tar.gz](https://github.com/dragonbook/V2V-PoseNet-pytorch/files/2697254/nyu.tar.gz)

**Comment by DongGuaDONG** [comment]
And MSRA' results is about 11mm mean error,why can't get Torch7'accuracy.

**Comment by dragonbook** [comment]
Hi, DongGuaDong,

Firstly, there are some small implementation differences  between this repository and the original one. e.g. no floor operation any more and how to apply 0.5 grid center offset etc(see src/v2v_util.py). But that should not affect the performance too much(you can check the code carefully if needed).

Actually, this repository and the simple msra demo only shows that the model can work, but not focus on the final precision(e.g. the paper's result has ensembled multiple models). Since I have not really compared with Torch7's implementation on same dataset and settings, there may exist some problems in my implementation. And I will experiment it in my spare time.

So, What' your Torch7's  accuracy on MSRA dataset? For your experiment on MSRA, can you post your configurations here? Configurations like:
(1) test subject id(e.g. default is 3)
(2) batch_size, 1, 2 or 8 etc?
(3) optimizer, adam or rmsprop?
(4) others?

**Comment by Limoran18** [comment]
Hi, I have also changed the code to NYU dataset. But the results seem like wrong. Is there any way to check whether my NYU code is right?

**Comment by dragonbook** [comment]
Related to [issue 6](https://github.com/dragonbook/V2V-PoseNet-pytorch/issues/6).

**Comment by happyCodingSusan** [comment]
@DongGuaDONG, it seems that you have got good results on MSRA dataset. May you share your model  for MSRA with me? 

Thank you very much.
